### ISSUE TITLE
Migrate tests and page objects back to services-test

### ISSUE THREAD

**Issue by cuff-links** [mozilla-services/services-test#117]

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla-services/services-marionette/issues/9

**Comment by rpappalax** [comment]
@silne30 is this complete?

**Comment by cuff-links** [comment]
@rpappalax No it isn't. We have dependencies on selenium since, as a group, we have decided to go with Selenium rather than Marionette for the bulk of our tests.

**Comment by rpappalax** [comment]
@silne30 OK, cool.  I'll go ahead and tag services-test w/ out worrying about this for now.

**Comment by cuff-links** [comment]
Cool beans. Thanks. 

J.D.

**Comment by rpappalax** [comment]
superseded by foxpuppet project
