### ISSUE TITLE
Simplify Firefox downloaden

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/services-test#19]
Looking at [./_shared/install_ff_nightly.sh](https://github.com/mozilla-services/services-test/blob/master/_shared/install_ff_nightly.sh), it may be slightly simpler if we use the lovely [**firefox-get**](https://github.com/jsantell/node-firefox-get) npm module (assumes the host images all have Node.js installed).

``` sh
$ curl $(firefox-get -v beta) | tar xz --directory ff_beta
```

**NOTE:** This assumes you already have an `./ff_beta/` directory.

We could also possibly abstract this one step further by creating some UNIX-y function where we pass a target "version" of Firefox that we want to download and it will ensure the directory is created for us.

Then we can do one/all of the following:
- `$ download_firefox release`
- `$ download_firefox beta`
- `$ download_firefox nightly`

From there we can create some ENV variables to point to the different Firefox versions, where `$FF_BETA` points to `./ff_beta/firefox/firefox-bin`.

**Comment by pdehaan** [comment]
Also, see this for downloading the *.common.tests.zip files (which I believe we're a usin' for Koki's Loop e2e tests): https://www.npmjs.com/package/common-tests-zip

> ### Basic:
> 
> The following example returns a link to the Mac OS X Firefox Nightly channel *.common.tests.zip:
> 
> ``` sh
> $ common-tests-zip -c nightly -o mac
> ```
> 
> ### Output:
> 
> ```
> https://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-trunk/firefox-43.0a1.en-US.mac.common.tests.zip
> ```

**Comment by pdehaan** [comment]
Scratch this, it looks like the delightfully handsome @rpappalax has found https://github.com/mozilla/mozdownload which will help us in downloading latest Firefoxen browsers and *.common.tests.zip files.

See [./loop/e2e-test/run.sh:28](https://github.com/mozilla-services/services-test/blob/2bda9f896efc5d34e10d5d7b2fc82c23a58d18de/loop/e2e-test/run.sh#L28) for example.

**Comment by rpappalax** [comment]
we got this!
