### ISSUE TITLE
[pep8] fix line length errors 

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/services-test#42]
flag lines with legit >80 length, then remove E501

**Comment by pdehaan** [comment]
![](http://www.reactiongifs.com/r/blrg.gif)

#qaoverruled

**Comment by pdehaan** [comment]
Here's the current list of `E501` errors via Flake8: https://gist.github.com/pdehaan/27010daff64c251cb012

**Comment by lavish205** [comment]
can I work on this bug? @pdehaan @rpappalax

**Comment by pdehaan** [comment]
@lavish205 yes please! Let us know if you need help or have any questions.

**Comment by pdehaan** [comment]
Fixed by #67
