### ISSUE TITLE
[mozdownload] replace _utils/firefox_download.py

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/services-test#53]
https://github.com/mozilla/mozdownload/issues/345

Mozdownload now fixed for OSX.  we should look at replacing our custom one:
https://github.com/mozilla-services/services-test/blob/dev/_utils/firefox_download.py

**Comment by pdehaan** [comment]
Our 4 envs that we need to support are:
1. **Nightly**: `mozdownload --type=daily --branch=mozilla-central`
2. **Aurora**: `mozdownload --type=daily --branch=mozilla-aurora`
3. **Beta**: `mozdownload --version=latest-beta`
4. **Release:** `mozdownload --version=latest`
