### ISSUE TITLE
fix: Modify all test run.sh / run.py files to drop file extension

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/services-test#57]
please include:

```
#!/usr/bin/env python
#!/usr/bin/env node
#!/usr/bin/env cobol
```

so then we can also leave off the file extension.
Since all our jenkins jobs are generated dynamically (and we can't assume one language), let's just drop the extension altogether.

For treeherder integration, we will probably need to go with either python or node:
see:  https://bugzilla.mozilla.org/show_bug.cgi?id=1213542#c8

README should also be updated accordingly

**Comment by pdehaan** [comment]
Node treeherder client: https://www.npmjs.com/package/mozilla-treeherder

**Comment by rpappalax** [comment]
These seem to be the only culprits:

pocket/e2e-test
pocket/security-test

Separate issues have been filed for projects not using run files (yet).
