### ISSUE TITLE
Merge /_temp with /_utils/_temp?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/services-test#58]
Currently we have a couple "floating" _temp folders
1. the root **/_temp/** folder is used for temporary Firefox Profiles (which we can clean up in the nightly refresh job).
2. We have a **/_utils/_temp/** folder is used for temporary Firefox binaries (added by #55 in [/_utils/firefox_download.py:41](https://github.com/mozilla-services/services-test/blob/3c8719d7ad177730b2f86d258d597ef8602146ad/_utils/firefox_download.py#L41))

We should maybe consider using **/_temp/profiles/** and **/_temp/firefoxes/**, or something.
This will keep everything close, and not have a bunch of random temporary folders peppered throughout the repo.

**Comment by pdehaan** [comment]
@rpappalax suggests sticking with /_utils/_temp/*

We probably want:
- /_utils/_temp/profiles
- /_utils/apps/{firefox binaries}
- /_utils/{random scripts}

**Comment by rpappalax** [comment]
@pdehaan: this is all being handled now by ff-tool, yes?  should we close this issue?

**Comment by pdehaan** [comment]
Me thinks so. :heart:
