### ISSUE TITLE
docs: Add to README note on best practices: i.e. - using virtualenv for python projects

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/services-test#65]
https://github.com/mozilla-services/services-test/search?utf8=%E2%9C%93&q=virtualenv&type=Code

We're doing `virtualenv .` in a couple places, which can make things a bit messy and hard to exclude when trying to grep or use globs in certain tools.

**Comment by rpappalax** [comment]
good catch.  I was thinking yesterday whether we should schedule a team mtg to standardize some things around automation.  we already decided on some last year, but a lot of water has gone under the bridge.

**Comment by pdehaan** [comment]
Long story longer, here was the greps I needed to run `autopep8` locally against the **services-test** repo:

``` sh
$ autopep8 -r --diff --exclude=**/venv/*,./kinto/bin/*,./kinto/lib/*,**/*.sikuli/*,./loop/e2e-test/marionette_env/*,**/node_modules/*,**/*.bak .
```

I'm sure this would be worse if I was working on a few other projects and happened to have more virtualenvs.

**Comment by rpappalax** [comment]
I think we'll have to address this on a project-by-project basis as a best practice.  This should probably be something added to the README.  I'll change the issue title accordingly.

**Comment by rpappalax** [comment]
this is really a best practice for python in general, but still we should add this on a per-project basis so going to close this issue (which is more directed at the over-arching README for all of services-test)
