### ISSUE TITLE
move services-marionette dir to _shared or separate repo

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/services-test#71]

**Comment by rpappalax** [comment]
If we move this to a separate repo, it would likely be more discoverable by folks looking for a quickstart project to bootstrap a marionette test.

**Comment by rpappalax** [comment]
https://github.com/mozilla-services/services-marionette
thanks, @pdehaan!
@silne30: you should be able to clone this and upload your lib whenever you're ready.  if you don't think it's ready for prime time, we can just set the default branch to dev for now

**Comment by pdehaan** [comment]
./services-marionette/ was neutered as of #90. Closing.
