### ISSUE TITLE
Add manifest.ini schema linting

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/services-test#80]
Ref: https://github.com/mozilla-services/services-test/blob/dev/sync/e2e-test/manifest.ini

True vs true
cron formatting 
prod vs production
job_timeout must be integer
required fields present
manifest file must define at least 3 envs (dev, stage, prod)

**Comment by rpappalax** [comment]
when would this ideally get run?  probably by travis when all other type of linting happens?
I'm thinking it could prob live in _utils dir.

**Comment by pdehaan** [comment]
Beats me, @rpappalax. I just say "linting" a lot to fool people into thinking i'm not a complete mouth breather. (is it working?)

I figure we could either do it on every commit via travis hook (maybe fail the build if the manifest.ini files aren't valid, so we cant merge until fixed).
Or maybe we just run it 1x a day on some cron, but then it'd probably be slightly trickier to give messaging on failures (send a message to IRC, notify via emails, etc).

**Comment by rpappalax** [comment]
this repo will be replace by individual repos. closing
